### ISSUE TITLE
Extension no longer works with latest builds of Firefox

### ISSUE THREAD

**Issue by geeknik** [HarmlessSystems/security.txt#26]
Good afternoon folks, just wanted to drop in and let you know that the extension has stopped working with the latest versions of Firefox. The extension installs just fine, there are no error messages in the console, however, there is no detection of security.txt or humans.txt taking place. In fact, the extension isn't even making a request for those files. I've tested on my own domains and third-party domains. Hoping it's an easy fix! Thanks.

**Comment by travispaul** [comment]
This is now fixed and has been published for Firefox. Thanks again for the report!
