### ISSUE TITLE
Add option to ignore certain sites?

### ISSUE THREAD

**Issue by geeknik** [HarmlessSystems/security.txt#6]
Hello and thank you for this useful browser extension. Would it be possible to add an option to ignore certain sites? For example, Feedly is highly incompatible with this extension and will actually block your IP after some time of reading your news feeds with this extension enabled. An alternative fix would be to make 1 check upon the initial page load and not check again unless a new tab is opened or the browser is restarted, etc.

**Comment by travispaul** [comment]
Hi @geeknik 
Thanks for reporting this issue. 

> Would it be possible to add an option to ignore certain sites?

Absolutely, we’ve also seen the extension break authentication flow on another site and have been considering adding such a feature.

> Feedly is highly incompatible with this extension and will actually block your IP after some time of reading your news feeds with this extension enabled.

I’m sorry that the extension caused you to get an IP block. We’ve not encountered that before. 

> An alternative fix would be to make 1 check upon the initial page load and not check again unless a new tab is opened or the browser is restarted, etc

We had considered that approach initially but had concerns about keeping a secondary cache/history of sites visited by the user, (even if only in memory) but might add that as a feature in a future release (perhaps disabled by default.)

For now, I think adding an option to disable  checks on certain sites might be the best approach. We’ll add this feature to the queue and get it out in the next release. 

Thanks again for using the extension and providing feedback.

**Comment by travispaul** [comment]
After a round of QA this week this feature will be added to the next release (v1.1.0)
